name: Push

on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2024.03.13'

    - name: Fetch code
      uses: actions/checkout@v2

    - name: Lint
      run: clj-kondo --lint src test --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'

  code-style:
    runs-on: ubuntu-latest
    steps:
    - name: Install cljstyle
      uses: 0918nobita/setup-cljstyle@v0.5.4
      with:
        cljstyle-version: "0.15.0"

    - name: Fetch code
      uses: actions/checkout@v2

    - name: Check code formatting
      run: cljstyle check

  test:
    runs-on: ubuntu-latest
    needs: [lint, code-style]
    steps:
    - name: Fetch code
      uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: latest

    - name: Test
      run: bin/kaocha
